### ISSUE TITLE
Plugins that has EntityDamageEvent throws errors

### ISSUE THREAD

**Issue by xhmr** [KibbleLands/KibblePatcher#6]
[00:55:39] [Server thread/WARN]: [ViaVersion] Task #17 for ViaVersion v3.2.1-SNAPSHOT generated an exception
java.lang.ClassFormatError: Duplicate method name "<init>" with signature "(Lorg.bukkit.entity.Entity;Lorg.bukkit.event.entity.EntityDamageEvent$DamageCause;D)V" in class file org/bukkit/event/entity/EntityDamageEvent
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_275]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:405) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_275]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_275]
	at java.lang.Class.privateGetPublicMethods(Class.java:2902) ~[?:1.8.0_275]
	at java.lang.Class.getMethods(Class.java:1615) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:236) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:460) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at us.myles.ViaVersion.bukkit.listeners.ViaBukkitListener.register(ViaBukkitListener.java:45) ~[?:?]
	at us.myles.ViaVersion.bukkit.platform.BukkitViaLoader.load(BukkitViaLoader.java:89) ~[?:?]
	at us.myles.ViaVersion.ViaManager.onServerLoaded(ViaManager.java:109) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by xhmr** [comment]
viaversion error when joining:
[00:57:19] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ClassFormatError: Duplicate method name "<init>" with signature "(Lorg.bukkit.entity.Entity;Lorg.bukkit.event.entity.EntityDamageEvent$DamageCause;D)V" in class file org/bukkit/event/entity/EntityDamageEvent
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_275]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"95870a93"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.ClassFormatError: Duplicate method name "<init>" with signature "(Lorg.bukkit.entity.Entity;Lorg.bukkit.event.entity.EntityDamageEvent$DamageCause;D)V" in class file org/bukkit/event/entity/EntityDamageEvent
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_275]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_275]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_275]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468) ~[?:1.8.0_275]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_275]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_275]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_275]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_275]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_275]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_275]
	at net.minecraft.server.v1_8_R3.EntityPlayer.a(EntityPlayer.java:917) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1730) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInSettings.a(SourceFile:52) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PacketPlayInSettings.a(SourceFile:9) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_275]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[spigot.jar:git-TacoSpigot-"95870a93"]
	... 5 more
[00:57:19] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_13To1_12_2 IN REMAP OF CHUNK_DATA (0x20)
[00:57:19] [Netty Epoll Server IO #1/WARN]: [ViaVersion] ERROR IN Protocol1_9To1_8 IN REMAP OF MAP_BULK_CHUNK (0x26)
[00:57:19] [Netty Epoll Server IO #1/WARN]: io.netty.handler.codec.EncoderException: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 2: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous), Source 1: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$5$1 (Anonymous)}
Actual Error: 
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:233)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:57:19] [Netty Epoll Server IO #1/WARN]: Caused by: us.myles.ViaVersion.exception.InformativeException: Please post this error to https://github.com/ViaVersion/ViaVersion/issues
{Source 0: us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9 (Anonymous), Source 2: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$5 (Anonymous), Source 1: us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$5$1 (Anonymous)}
Actual Error: 
[00:57:19] [Netty Epoll Server IO #1/WARN]: Caused by: java.lang.NullPointerException
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.blockconnections.ConnectionData.needStoreBlocks(ConnectionData.java:159)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_13to1_12_2.packets.WorldPackets$9$1.handle(WorldPackets.java:362)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.constructPacket(PacketWrapper.java:344)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.send(PacketWrapper.java:301)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.protocols.protocol1_9to1_8.packets.WorldPackets$5$1.handle(WorldPackets.java:164)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketHandler.write(PacketHandler.java:19)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.remapper.PacketRemapper.remap(PacketRemapper.java:131)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.Protocol.transform(Protocol.java:407)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:449)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.PacketWrapper.apply(PacketWrapper.java:435)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.transform(ProtocolPipeline.java:75)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transform(UserConnection.java:404)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.api.data.UserConnection.transformOutgoing(UserConnection.java:379)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.transform(BukkitEncodeHandler.java:66)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at us.myles.ViaVersion.bukkit.handlers.BukkitEncodeHandler.encode(BukkitEncodeHandler.java:59)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:233)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[00:57:19] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[00:57:19] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException
[00:57:19] [Netty Epoll Server IO #1/WARN]: java.nio.channels.ClosedChannelException

**Comment by Fox2Code** [comment]
@assasin541 Thanks for reporting!
The new release fixed the issue!
you can download here:
https://github.com/KibbleLands/KibblePatcher/releases/tag/1.4
Also don't hesitate to join the kibbleLand Discord server!
https://discord.gg/qgk4Saq
